**NumPY= Numerical Python** >> pythonda sayısal hesaplamalar için. ÇOK BOYUTLU DİZİLERLE (array) . Arraylerle
yapılacak zor işleri kolaylaştırır.

In [3]:
my_list= [1,2,3, [0,1] , [2,3,5] ] 

In [4]:
my_list[4]

[2, 3, 5]

NDARRAY  numPY'nin temel veri yapısı. Bunun sayesinde optimal olur ve kompakt olur. 


NEREDE PANDAS NEREDE NUMPY KULLANACAĞIZ.

matematik/ model matris/ büyük sayısal hesaplar >>> numPY
veri temizleme/ veriyi birleştirmek/ gruplamak ve raporlamak >> PANDAS 



In [5]:
import numpy as np

ben_tek_boyutlu_bir_diziyim= np.array([1,2,3] ) # tek boyutlu bir dizi
ben_iki_boyutlu_bir_diziyim= np.array( [ [1,2,3] , [4,5,6] ] ) #iki boyutlu bir dizi

In [6]:
type(ben_iki_boyutlu_bir_diziyim)

numpy.ndarray

In [12]:
(ben_tek_boyutlu_bir_diziyim.shape), (ben_iki_boyutlu_bir_diziyim.shape)

((3,), (2, 3))

In [9]:
ben_iki_boyutlu_bir_diziyim

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a = np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
print(a)

[[0. 0.]
 [0. 0.]]


In [16]:
b= np.ones( (3,2) )
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
c= np.full( (2,2) , 7.9 )
c

array([[7.9, 7.9],
       [7.9, 7.9]])

In [26]:
d= np.eye(5) #identy matris BİRİM MATRİS, SATIRI SÜTUNUNA EŞİT, ÇAPRAZLAMANIN ADI DA DİYAGONAL.
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
e= np.random.random( (3,3) )  # 0 İLE 1 ARASINDA 
e

array([[0.352131  , 0.41952476, 0.62864368],
       [0.76912776, 0.562573  , 0.94307181],
       [0.36514792, 0.26287545, 0.78776699]])

DATA İNDEKSLEME
